# Setup
title:               Learning blog of Dohyun Lee
tagline:             ''
description:         'A personal space where Dohyun collects learning notes, development logs, and project reflections.'
url:                 https://karcazr.github.io
baseurl:             /blog
paginate:            5
permalink:           pretty
exclude:
  - _site_local

# About/contact
author:
  name:              Dohyun
  url:
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
